# inherit_from: './.rubocop_todo.yml'

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'Rakefile'
    - 'Gemfile'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/LineLength:
    Max: 120
