source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'jbuilder', '~> 2.0'

gem 'sqlite3'

gem 'bcrypt', '~> 3.1.7'
gem 'twilio-ruby'

gem 'parslet'

# Use Unicorn as the app server
gem 'unicorn'

group :test do
  gem 'simplecov', require: false
  gem 'factory_girl_rails', '~> 4.0'
end

group :development, :test do
  gem 'byebug'
  gem 'pry', require: false
  gem 'rspec-rails', '~> 3.0'
  gem 'forgery'
end

group :development do
  gem 'rubocop', require: false
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'fuubar'
  gem 'immigrant'
end
